[2025-08-16 22:24:36,998] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_dbt_analytics_schema manual__2025-08-16T22:24:29.163570+00:00 [queued]>
[2025-08-16 22:24:37,007] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_dbt_analytics_schema manual__2025-08-16T22:24:29.163570+00:00 [queued]>
[2025-08-16 22:24:37,009] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 22:24:37,010] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-16 22:24:37,012] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 22:24:37,022] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_dbt_analytics_schema> on 2025-08-16 22:24:29.163570+00:00
[2025-08-16 22:24:37,028] {standard_task_runner.py:52} INFO - Started process 156 to run task
[2025-08-16 22:24:37,033] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '1_load_initial_data', 'create_dbt_analytics_schema', 'manual__2025-08-16T22:24:29.163570+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/initialise_data.py', '--cfg-path', '/tmp/tmpvzrnzahh', '--error-file', '/tmp/tmps7n8v1gz']
[2025-08-16 22:24:37,038] {standard_task_runner.py:80} INFO - Job 22: Subtask create_dbt_analytics_schema
[2025-08-16 22:24:37,168] {task_command.py:369} INFO - Running <TaskInstance: 1_load_initial_data.create_dbt_analytics_schema manual__2025-08-16T22:24:29.163570+00:00 [running]> on host f4989c8fe60b
[2025-08-16 22:24:37,273] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=1_load_initial_data
AIRFLOW_CTX_TASK_ID=create_dbt_analytics_schema
AIRFLOW_CTX_EXECUTION_DATE=2025-08-16T22:24:29.163570+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-16T22:24:29.163570+00:00
[2025-08-16 22:24:37,274] {sql.py:262} INFO - Executing: CREATE SCHEMA IF NOT EXISTS dbt_analytics;
[2025-08-16 22:24:37,290] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 22:24:37,328] {logging_mixin.py:115} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/connection.py:339 DeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2025-08-16 22:24:37,348] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 22:24:37,366] {sql.py:375} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS dbt_analytics;, parameters: None
[2025-08-16 22:24:37,387] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1_load_initial_data, task_id=create_dbt_analytics_schema, execution_date=20250816T222429, start_date=20250816T222437, end_date=20250816T222437
[2025-08-16 22:24:37,451] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-16 22:24:37,516] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
