[2025-08-16 21:25:31,747] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_business_types manual__2025-08-16T21:25:27.221750+00:00 [queued]>
[2025-08-16 21:25:31,756] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_business_types manual__2025-08-16T21:25:27.221750+00:00 [queued]>
[2025-08-16 21:25:31,758] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 21:25:31,759] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-16 21:25:31,760] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 21:25:31,770] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_business_types> on 2025-08-16 21:25:27.221750+00:00
[2025-08-16 21:25:31,777] {standard_task_runner.py:52} INFO - Started process 330 to run task
[2025-08-16 21:25:31,781] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '1_load_initial_data', 'create_business_types', 'manual__2025-08-16T21:25:27.221750+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/initialise_data.py', '--cfg-path', '/tmp/tmpnlo13hbq', '--error-file', '/tmp/tmpq3ctukls']
[2025-08-16 21:25:31,783] {standard_task_runner.py:80} INFO - Job 9: Subtask create_business_types
[2025-08-16 21:25:31,866] {task_command.py:369} INFO - Running <TaskInstance: 1_load_initial_data.create_business_types manual__2025-08-16T21:25:27.221750+00:00 [running]> on host 6a6e6aafe640
[2025-08-16 21:25:31,954] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=1_load_initial_data
AIRFLOW_CTX_TASK_ID=create_business_types
AIRFLOW_CTX_EXECUTION_DATE=2025-08-16T21:25:27.221750+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-16T21:25:27.221750+00:00
[2025-08-16 21:25:31,958] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS dbt_raw_data.business_types (
        initcap VARCHAR(64),
        active BOOLEAN,
        business_type_id INT PRIMARY KEY
    );
    
[2025-08-16 21:25:31,979] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 21:25:32,002] {logging_mixin.py:115} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/connection.py:339 DeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2025-08-16 21:25:32,023] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 21:25:32,033] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS dbt_raw_data.business_types (
        initcap VARCHAR(64),
        active BOOLEAN,
        business_type_id INT PRIMARY KEY
    );
    , parameters: None
[2025-08-16 21:25:32,056] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1_load_initial_data, task_id=create_business_types, execution_date=20250816T212527, start_date=20250816T212531, end_date=20250816T212532
[2025-08-16 21:25:32,113] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-16 21:25:32,150] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
