[2025-08-16 22:24:30,985] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.drop_table_dim_fecha manual__2025-08-16T22:24:29.163570+00:00 [queued]>
[2025-08-16 22:24:31,000] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.drop_table_dim_fecha manual__2025-08-16T22:24:29.163570+00:00 [queued]>
[2025-08-16 22:24:31,002] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 22:24:31,003] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-16 22:24:31,004] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 22:24:31,019] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): drop_table_dim_fecha> on 2025-08-16 22:24:29.163570+00:00
[2025-08-16 22:24:31,037] {standard_task_runner.py:52} INFO - Started process 132 to run task
[2025-08-16 22:24:31,085] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '1_load_initial_data', 'drop_table_dim_fecha', 'manual__2025-08-16T22:24:29.163570+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/initialise_data.py', '--cfg-path', '/tmp/tmpjoyttqtr', '--error-file', '/tmp/tmpunguwv6x']
[2025-08-16 22:24:31,113] {standard_task_runner.py:80} INFO - Job 11: Subtask drop_table_dim_fecha
[2025-08-16 22:24:31,378] {task_command.py:369} INFO - Running <TaskInstance: 1_load_initial_data.drop_table_dim_fecha manual__2025-08-16T22:24:29.163570+00:00 [running]> on host f4989c8fe60b
[2025-08-16 22:24:31,629] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=1_load_initial_data
AIRFLOW_CTX_TASK_ID=drop_table_dim_fecha
AIRFLOW_CTX_EXECUTION_DATE=2025-08-16T22:24:29.163570+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-16T22:24:29.163570+00:00
[2025-08-16 22:24:31,631] {sql.py:262} INFO - Executing: DROP TABLE IF EXISTS dbt_raw_data.dim_fecha;
[2025-08-16 22:24:31,651] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 22:24:31,692] {logging_mixin.py:115} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/connection.py:339 DeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2025-08-16 22:24:31,711] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 22:24:31,728] {sql.py:375} INFO - Running statement: DROP TABLE IF EXISTS dbt_raw_data.dim_fecha;, parameters: None
[2025-08-16 22:24:31,782] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1_load_initial_data, task_id=drop_table_dim_fecha, execution_date=20250816T222429, start_date=20250816T222430, end_date=20250816T222431
[2025-08-16 22:24:31,832] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-16 22:24:31,919] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
