[2025-08-16 23:00:24,643] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_dbt_analytics_schema manual__2025-08-16T23:00:08.759833+00:00 [queued]>
[2025-08-16 23:00:24,656] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_dbt_analytics_schema manual__2025-08-16T23:00:08.759833+00:00 [queued]>
[2025-08-16 23:00:24,658] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 23:00:24,659] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-16 23:00:24,660] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 23:00:24,674] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_dbt_analytics_schema> on 2025-08-16 23:00:08.759833+00:00
[2025-08-16 23:00:24,684] {standard_task_runner.py:52} INFO - Started process 165 to run task
[2025-08-16 23:00:24,688] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '1_load_initial_data', 'create_dbt_analytics_schema', 'manual__2025-08-16T23:00:08.759833+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/initialise_data.py', '--cfg-path', '/tmp/tmp2vdirbrt', '--error-file', '/tmp/tmpkx4mnh2j']
[2025-08-16 23:00:24,691] {standard_task_runner.py:80} INFO - Job 21: Subtask create_dbt_analytics_schema
[2025-08-16 23:00:24,762] {task_command.py:369} INFO - Running <TaskInstance: 1_load_initial_data.create_dbt_analytics_schema manual__2025-08-16T23:00:08.759833+00:00 [running]> on host 03b58f608368
[2025-08-16 23:00:24,828] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=1_load_initial_data
AIRFLOW_CTX_TASK_ID=create_dbt_analytics_schema
AIRFLOW_CTX_EXECUTION_DATE=2025-08-16T23:00:08.759833+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-16T23:00:08.759833+00:00
[2025-08-16 23:00:24,830] {sql.py:262} INFO - Executing: CREATE SCHEMA IF NOT EXISTS dbt_analytics;
[2025-08-16 23:00:24,844] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 23:00:24,871] {logging_mixin.py:115} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/connection.py:339 DeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2025-08-16 23:00:24,884] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 23:00:24,897] {sql.py:375} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS dbt_analytics;, parameters: None
[2025-08-16 23:00:24,919] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1_load_initial_data, task_id=create_dbt_analytics_schema, execution_date=20250816T230008, start_date=20250816T230024, end_date=20250816T230024
[2025-08-16 23:00:24,941] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-16 23:00:24,975] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
