[2025-08-16 23:00:14,308] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.drop_table_dim_fecha manual__2025-08-16T23:00:08.759833+00:00 [queued]>
[2025-08-16 23:00:14,315] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.drop_table_dim_fecha manual__2025-08-16T23:00:08.759833+00:00 [queued]>
[2025-08-16 23:00:14,316] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 23:00:14,317] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-16 23:00:14,318] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 23:00:14,330] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): drop_table_dim_fecha> on 2025-08-16 23:00:08.759833+00:00
[2025-08-16 23:00:14,334] {standard_task_runner.py:52} INFO - Started process 143 to run task
[2025-08-16 23:00:14,340] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '1_load_initial_data', 'drop_table_dim_fecha', 'manual__2025-08-16T23:00:08.759833+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/initialise_data.py', '--cfg-path', '/tmp/tmpj7o6pqa3', '--error-file', '/tmp/tmptyoskefg']
[2025-08-16 23:00:14,349] {standard_task_runner.py:80} INFO - Job 9: Subtask drop_table_dim_fecha
[2025-08-16 23:00:14,433] {task_command.py:369} INFO - Running <TaskInstance: 1_load_initial_data.drop_table_dim_fecha manual__2025-08-16T23:00:08.759833+00:00 [running]> on host 03b58f608368
[2025-08-16 23:00:14,548] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=1_load_initial_data
AIRFLOW_CTX_TASK_ID=drop_table_dim_fecha
AIRFLOW_CTX_EXECUTION_DATE=2025-08-16T23:00:08.759833+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-16T23:00:08.759833+00:00
[2025-08-16 23:00:14,552] {sql.py:262} INFO - Executing: DROP TABLE IF EXISTS dbt_raw_data.dim_fecha;
[2025-08-16 23:00:14,588] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 23:00:14,623] {logging_mixin.py:115} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/connection.py:339 DeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2025-08-16 23:00:14,635] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 23:00:14,648] {sql.py:375} INFO - Running statement: DROP TABLE IF EXISTS dbt_raw_data.dim_fecha;, parameters: None
[2025-08-16 23:00:14,672] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1_load_initial_data, task_id=drop_table_dim_fecha, execution_date=20250816T230008, start_date=20250816T230014, end_date=20250816T230014
[2025-08-16 23:00:14,716] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-16 23:00:14,762] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
